name: portainer

volumes:
  portainer-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./Portainer/data


services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.40.0-alpine
    volumes:
      - portainer-data:/data
      #      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      #      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    networks:
      - portainer

networks:
  portainer:
    driver: bridge