services:
  redis:
    container_name: redis
    image: redis:7.4.6-alpine3.21
    volumes:
      #      - ./config/redis/redis.conf:/etc/redis.conf
      - ./data/redis:/data
    ports:
      - "6379:6379"
    #    restart: always
    networks:
      - iufc