apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine3.23-perl
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi