apiVersion: v1
kind: Secret
metadata:
  name: secret-config
  namespace: secret
type: kubernetes.io/basic-auth
stringData:
  username: "username"
  password: "password"


---
# 方式一:  键值对使用配置文件
apiVersion: v1
kind: Pod
metadata:
  name: alpine-configmap
  namespace: secret
spec:
  containers:
    - name: alpine
      image: harbor.xujian.org.cn/library/alpine:xxx
      command: ["/bin/sh", "-c", "env;sleep 3600"]
      imagePullPolicy: IfNotPresent
      env:                                      # 环境变量名称
        - name: username                        # 环境变量名称
          valueFrom:
            secretKeyRef:                       # 引入 Secret 中引入 Key
              name: secret-config               # Secret 名称
              key: username                     # 从 name 的 Secret 中获取名称为 key 的 value, 将其赋值给本地环境变量 username
        - name: password
          valueFrom:
            secretKeyRef:
              key: password
              name: secret-config
  restartPolicy: Always

---
# 方式二: 文件使用配置文件
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    role: alpine
spec:
  containers:
    - name: alpine
      image: harbor.xujian.org.cn/library/alpine:xxx
      command: ["/bin/sh", "-c", "env;sleep 3600"]
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /etc/mysql/conf
          name: db-config
          readOnly: true
  volumes:                                  # 数据卷挂载 ConfigMap/Secret
    - name: db-config                       # 数据卷名称: 随意设置
      secret:                               # 数据卷类型 Secret
        secretName: secret-config           # Secret 名称, 必须跟想要加载的 Secret 相同
        items:                              # 对 Secret 中的 key 进行映射, 如果不指定, 默认会将 Secret 中所有 key 全部转换为一个个同名的文件
          - key: username                   # Secret 中的 Key
            path: "db.properties"           # 将该 Key 转换为文件
          - key: password
            path: "db.properties"
  restartPolicy: Always

---
# 方式三: SubPath 使用
# 方式三: SubPath 使用
apiVersion: v1
kind: Pod
metadata:
  name: alpine-configmap3
  namespace: configmap
spec:
  containers:
    - name: alpine
      image: harbor.xujian.org.cn/library/alpine:3.20
      command: ["/bin/sh", "-c", "env;sleep 3600"]
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /etc/nginx/nginx.conf          # 挂载容器内位置
          name: nginx-conf                          # 使用 ConfigMap 或 Secret, voluems[0].name
          subPath: etc/nginx/nginx.conf             # # volumes[0].items.path 相同
  volumes:
    - name: nginx-conf                              # 数据卷名称: 随意设置, 挂载时使用
      secret:
        secretName: secret-config
        items:
          - key: username
            path: etc/xxx
  restartPolicy: Always