apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
  namespace: nginx-namespace
spec:
  containers:
  - name: nginx-pod
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    command:
      - nginx
      - -g
      - 'daemon off;'
    workingDir: /usr/share/nginx/html
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    env:
      - name: nginx
        value: '/usr/local'
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 400Mi
  restartPolicy: Always 
