name: hadoop
services:
  namenode:
    build: ./config/hadoop
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    env_file:
      - ./config/hadoop/config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  datanode:
    build: ./config/hadoop
    command: ["hdfs", "datanode"]
    env_file:
      - ./config/hadoop/config
  resourcemanager:
    build: ./config/hadoop
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./config/hadoop/config
#    volumes:
#      - ./test.sh:/opt/test.sh
  nodemanager:
    build: ./config/hadoop
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config/hadoop/config