services:
  nginx:
    container_name: nginx
    image: nginx:stable-perl
    volumes:
      - ./Config/nginx/conf.d:/etc/nginx/conf.d
      - ./Config/nginx/html:/usr/share/nginx/html
    #    restart: always
    expose:
      - "30080:80"
    ports:
      - "30080:80"
    deploy:
      replicas: 1
    networks:
      - develop
  ## N8N
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./N8N:/home/node/.n8n
    networks:
      - develop

  xxljob:
    container_name: xxljob
    image: openjdk:8-jdk
    volumes:
      - ./XxlJob:/opt/XxlJob
    networks:
      - develop
  #  gitea:
  #    container_name: gitea
  #    networks:
  #      - develop
  jenkins:
    container_name: jenkins
    image:  jenkins/jenkins:jdk21
    privileged: true
    user: root
    volumes:
      - ./Jenkins:/var/jenkins_home
    #    environment:
    #      JENKINS_OPTS: "--prefix=/jenkins"
    ports:
      - "38080:8080"
    networks:
      - develop