services:
  redis:
    container_name: redis
    image: redis:7.4.6-alpine3.21
    privileged: true
    volumes:
      - ./Redis:/data
    ports:
      - "36379:6379"
    networks:
      - develop
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.28
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      discovery.type: single-node
    ports:
      - "39200:9200"
      - "39300:9300"
    networks:
      - develop
  kibana:
    container_name: kibana
    image: kibana:7.17.28
    ports:
      - "35601:5601"
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - develop