services:
  mysql:
    container_name: mysql
    image: ${MYSQL_IMAGE}
    privileged: true
    env_file:
      - ../.env
    ports:
      - "33306:3306"
    volumes:
      - ./Config/MySQL/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      #      - ./Config/MySQL/conf.d:/etc/mysql/conf.d
      - ./Data/MySQL/log:/var/log/mysql
      - ./Data/MySQL/data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - develop

  postgresql:
    container_name: postgresql
    image: postgres:14.19-alpine3.21
    privileged: true
    volumes:
      - ./PostgreSQL/data:/var/lib/postgresql/data
      - ./Config/PostgreSQL/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "35432:5432"
    networks:
      - develop


  #
  #  nacos:
  #    container_name: nacos
  #    image: nacos/nacos-server:v2.3.2-slim
  #    environment:
  #      MODE: standalone
  #      PREFER_HOST_MODE: hostname
  #      MYSQL_SERVICE_HOST: mysql3306
  #      MYSQL_SERVICE_PORT: 3306
  #      SPRING_DATASOURCE_PLATFORM: mysql
  #      MYSQL_SERVICE_DB_NAME: nacos_config
  #      MYSQL_SERVICE_USER: nacos
  #      MYSQL_SERVICE_PASSWORD: Nacos@1234
  #      MYSQL_DATABASE_NUM: 1
  #      MYSQL_SERVICE_DB_PARAM: allowPublicKeyRetrieval=true&&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
  #    ports:
  #      - "38848:8848"
  #      - "39848:9848"
  #    healthcheck:
  #      test: [ "CMD", "curl" ,"-f", "http://localhost:8848/nacos/v2/core/cluster/node/self/health" ]
  #      interval: 5s
  #      timeout: 10s
  #      retries: 10
  #    depends_on:
  #      mysql3306:
  #        condition: service_healthy
  #    #    restart: always
  #    networks:
  #      - develop

