name: prometheus
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.11.3
    volumes:
      - "./data/prometheus:/prometheus"
#    entrypoint:
#      - "/bin/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=7d"
    ports:
      - "9090:9090"
    networks:
      - prom

  grafana:
    container_name: grafana
    image: grafana/grafana:13.1.0-25141410377
    volumes:
      - "./data/grafana:/var/lib/grafana"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - prom

networks:
  prom:
    driver: bridge

# docker run --name prometheus -d -p 127.0.0.1:9090:9090 prom/prometheus
#  docker run -d --name=grafana -p 3000:3000 grafana/grafana
