name: arthas

services:
  arthas:
    build:
      context: .
      dockerfile: Dockerfile/arthas/arthas.dockerfile
    command: [ "java","-jar", "/opt/arthas/math-game.jar" ]
    privileged: true
    networks:
      - arthas
networks:
  arthas:
    driver: bridge