name: hadoop
services:
  namenode:
    build: ./Dockerfile/hadoop
    container_name: hadoop-namenode
    environment:
      - ROLE=namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    networks:
      - hadoop

  resourcemanager:
    build: ./Dockerfile/hadoop
    container_name: hadoop-resourcemanager
    environment:
      - ROLE=resourcemanager
    ports:
      - "8088:8088"
      - "8032:8032"
    depends_on:
      - namenode
    networks:
      - hadoop

  datanode1:
    build: ./Dockerfile/hadoop
    container_name: hadoop-datanode1
    environment:
      - ROLE=datanode
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop

  datanode2:
    build: ./Dockerfile/hadoop
    container_name: hadoop-datanode2
    environment:
      - ROLE=datanode
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop

  nodemanager1:
    build: ./Dockerfile/hadoop
    container_name: hadoop-nodemanager1
    environment:
      - ROLE=nodemanager
    depends_on:
      - resourcemanager
    networks:
      - hadoop

  nodemanager2:
    build: ./Dockerfile/hadoop
    container_name: hadoop-nodemanager2
    environment:
      - ROLE=nodemanager
    depends_on:
      - resourcemanager
    networks:
      - hadoop
networks:
  hadoop:
