name: mysql
services:
  # MySQL
  mysql-master:
    image: mysql:8.4.1
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/master/data:/var/lib/mysql
      - ./data/mysql/master/log:/var/log/mysql
      - ./mysql/master/conf.d:/etc/mysql/conf.d
    networks:
      - mysql
  # MySQL
  mysql-slave:
    image: mysql:8.4.1
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql/slave/data:/var/lib/mysql
      - ./data/mysql/slave/log:/var/log/mysql
      - ./config/mysql/slave/conf.d:/etc/mysql/conf.d
    networks:
      - mysql
networks:
  mysql:

