name: arthas
services:
  arthas:
    image: openjdk:21-ea-jdk
    container_name: arthas
    volumes:
      - ./data/arthas:/opt/arthas
    command:
      - tail
      - -f
      - /dev/null

      #    build:
      #      context: ./Dockerfile
      #      dockerfile: ./Dockerfile/arthas.dockerfile
#      - java
      #      - -javaagent:/opt/arthas/arthas-agent.jar
#      - -jar
#      - /opt/arthas/math-game.jar
    networks:
      - arthas
  tunnel:
    image: openjdk:21-ea-jdk
    container_name: tunnel
    volumes:
      - ./data/tunnel:/opt/tunnel
    ports:
      - "8080:8080"
    command:
      - tail
      - -f
      - /dev/null
#      - java
#      - -jar
#      - /opt/tunnel/arthas-tunnel-server-4.0.5-fatjar.jar
    networks:
      - arthas
#  tunnel_server:
#    container_name: tunnel_server
#    image: tunnel-tunnel-server:4.0.5
#    build:
#      context: ./Dockerfile  # 目录
#      dockerfile: arthas.dockerfile
#    networks:
#      - arthas

networks:
  arthas:
    driver: bridge