version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx:stable-perl
    volumes:
      - ./Config/nginx/conf.d:/etc/nginx/conf.d
      - ./Config/nginx/html:/usr/share/nginx/html
    #    restart: always
#    expose:
#      - "30080:80"
    ports:
      - "30080:80"
    deploy:
      replicas: 1
    networks:
      - nginx
networks:
  nginx:
    driver: bridge
