version: "3"
services:
  xxl-job:
    container_name: xxl-job
    image: openjdk:8-jdk
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://xxl-job-mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JAVA_OPTS=-Xms512m -Xmx1024m  # 示例：设置 Java 启动参数
#    command: sh -c "echo $JAVA_VERSION"
    command:
      - sh
      - -c
      - 'java $$JAVA_OPTS -jar /opt/xxl-job-admin-2.4.2-SNAPSHOT.jar --spring.datasource.url=$$SPRING_DATASOURCE_URL --spring.datasource.username=$$SPRING_DATASOURCE_USERNAME --spring.datasource.password=$$SPRING_DATASOURCE_PASSWORD'
    volumes:
      - ./xxl-job:/opt
    ports:
      - "9000:8080"
    networks:
      - xxljob
  xxl-job-mysql:
    container_name: xxl-job-mysql
    image: mysql:8.4.1
    #    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xxl_job
      MYSQL_USER: xujian
      MYSQL_PASSWORD: xujian
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - xxljob
networks:
  xxljob:
    driver: bridge


