upstream nacos {
	server nacos1:8848;
	server nacos2:8848;
	server nacos3:8848;
}
# upstream nacos9848 {
#     ip_hash;
# 	server nacos1:9848;
# 	server nacos2:9848;
# 	server nacos3:9848;
# }

server {
    listen       8848;
#     listen  [::]:8848;

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
    location / {
           # root   html;
           index  index.html index.htm;
           proxy_pass http://nacos;
    }

}

#
# server {
#     listen       9848;
#     listen  [::]:9848;
#     server_name  localhost;
#
#     error_page   500 502 503 504  /50x.html;
#     location = /50x.html {
#         root   /usr/share/nginx/html;
#     }
#     location / {
#            # root   html;
#            index  index.html index.htm;
#            proxy_pass http://nacos:9848;
#     }
#
# }
